name: Deploy Logs Services to EC2

on:
  push:
    branches:
      - test  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up SSH key for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_PEM_KEY }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker images for logs services
      run: |
        docker build -t kamartinez/sql-logs ./Sql_logs
        docker build -t kamartinez/time ./date-time-service

    - name: Push images to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push kamartinez/sql-logs
        docker push kamartinez/time

    - name: Deploy services to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 54.89.45.221
        username: ec2-user
        key: ${{ secrets.EC2_PEM_KEY }}
        script: |
          docker stop sql-logs || true
          docker rm sql-logs || true
          docker stop time || true
          docker rm time || true

          docker pull kamartinez/sql-logs
          docker pull kamartinez/time

          docker run -d --name sql-logs -p 5000:5000 kamartinez/sql-logs
          docker run -d --name time -p 5001:5001 kamartinez/time
